### ISSUE TITLE
Useless command for travis

### ISSUE THREAD

**Issue by RobolabGs2** [mmcs-ruby/silicium#13]
[Скриптом в travis для ruby](https://docs.travis-ci.com/user/languages/ruby/#default-build-script) является `rake`, а для `rake` у нас 
https://github.com/mmcs-ruby/silicium/blob/e96a91387af519af40545ce17a4910e64e381580/Rakefile#L10
Т.е. скрипт прогонит тесты. При этом
https://github.com/mmcs-ruby/silicium/blob/e96a91387af519af40545ce17a4910e64e381580/.travis.yml#L7
Перед деплоем тесты прогонятся ещё раз. Хотя если тесты прошли, то смысла их запускать снова нет, а если не прошли, то [деплой не запустится](https://docs.travis-ci.com/user/job-lifecycle/#deploying-your-code).

> The deploy steps are skipped if the build is broken.

Т.е. смысла в прогоне тестов снова перед деплоем не вижу. Или я что-то проморгал?

**Comment by Wolwer1nE** [comment]
Отличное замечание!
Проверил - все так, тесты прогоняются дефолтным таском.
В мастере исправленная версия.
Аналогично в fast_matrix надо сделать.

Странно, что на времени сборки не сказалось:
![изображение](https://user-images.githubusercontent.com/466149/67373234-f3221d00-f587-11e9-8fd6-5168611fdb16.png)
