### ISSUE TITLE
Add more geometry functions

### ISSUE THREAD

**Issue by violetta0012** [mmcs-ruby/silicium#18]
A few ideas what should be added to Geometry 

- [ ] Check if point is on a segment or plane
- [ ] Check if lines or planes are parallel or intersecting or perpendicular
- [ ] Distance between parallel lines or planes
- [ ] Distance from point or line to plane
- [ ] Check if points from array are on the same line or plane

**Comment by Wolwer1nE** [comment]
@violetta0012 can you mark progress on this issue, please?

**Comment by nsilantev91** [comment]
Start working with Elena Varlamova(@elenavarl)
