### ISSUE TITLE
Vertical line cannot be initialized in Line2DCanon

### ISSUE THREAD

**Issue by violetta0012** [mmcs-ruby/silicium#29]
I get an exception when I try to initialize a vertical line. But they exist and I want to use them.

**Comment by Lereena** [comment]
Just pinging @Immoraly to know if they can manage that

**Comment by violetta0012** [comment]
My suggestion is to implement another equation: _Ax + By + C = 0_ or _(x - x0)/l = (y - y0)/m_.

**Comment by violetta0012** [comment]
We discussed it and decided that I would fix it.
