### ISSUE TITLE
Can't make a pull request

### ISSUE THREAD

**Issue by semyondv** [mmcs-ruby/silicium#73]
Ruby 2D Installation Errors
=======================================
  Couldn't find packages needed by Ruby 2D.
  Install the following packages using `apt` and try again:
    libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
  
  See ruby2d.com for additional help.

how to install this packages ?

**Comment by Wolwer1nE** [comment]
Solved.
